# Generated by Django 6.0.7 on 2026-08-15 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('skills', models.TextField(help_text='Separate skills using commas or |')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
