# Generated by Django 6.0.7 on 2026-08-15 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeanalysis',
            name='ats_feedback',
            field=models.TextField(blank=True),
        ),
    ]
